img_folder: ../sfcmap
data_folder: ../DATA

detectH:
  output_html: html/detectH.html
  start: 2019-11-01 00:00
  end: 2019-11-03 23:59

detectH_latlongrid:
  output_html: html/detectH_latlongrid.html
  start: 2024-10-01 00:00
  end: 2025-03-30 23:59

detectH_multipleperiods:
  output_html: html/detectH_multipleperiods.html
  time_ranges:
    - [2016-12-13 22:00, 2016-12-16 23:00]
    - [2017-01-13 00:30, 2017-01-16 19:00]
    - [2017-01-19 23:30, 2017-01-26 19:00]
    - [2017-01-30 08:00, 2017-02-02 22:00]
    - [2017-02-08 20:30, 2017-02-11 23:30]
    - [2017-02-23 10:00, 2017-02-27 19:30]
    - [2022-10-09 05:30, 2022-10-19 22:00]
    - [2022-10-28 08:30, 2022-11-02 22:30]
    - [2022-11-03 20:00, 2022-11-07 00:00]
    - [2022-11-30 01:00, 2022-12-15 09:00]
    - [2023-01-15 00:00, 2023-01-21 19:00]
    - [2023-02-02 01:00, 2023-02-06 02:00]
    - [2023-02-13 18:00, 2023-02-17 00:00]
